### ISSUE TITLE
Crashes with Error: rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by ssherbondy** [kvrhdn/terraform-provider-honeycombio#53] opened 2021-02-19 03:27 UTC
Running `terraform plan` works successfully. But running `terraform apply` crashes with Error: rpc error: code = Unavailable desc = transport is closing

## Versions
```
Terraform v0.14.7
+ provider registry.terraform.io/kvrhdn/honeycombio v0.1.2
```

## Terraform Config
Below is the config in main.tf
```
terraform {
  required_providers {
    honeycombio = {
      source  = "kvrhdn/honeycombio"
      version = "~> 0.1.2"
    }
  }
}

data "honeycombio_query" "query" {
  calculation {
    op     = "COUNT"
  }
  time_range = 120
}

resource "honeycombio_trigger" "trigger" {
  name        = "test"
  description = "test"
  disabled = false
  query_json = data.honeycombio_query.query.json
  dataset    = "ssherbondy-dev"
  frequency = 120 
  threshold {
    op    = ">"
    value = 300000
  }
}
```

## Error output
Below is the output from `terraform apply`:
```
Error: rpc error: code = Unavailable desc = transport is closing


panic: runtime error: invalid memory address or nil pointer dereference
2021-02-18T22:13:20.426-0500 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1695547]
2021-02-18T22:13:20.426-0500 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2:
2021-02-18T22:13:20.426-0500 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: goroutine 49 [running]:
2021-02-18T22:13:20.427-0500 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: github.com/kvrhdn/terraform-provider-honeycombio/honeycombio.resourceTriggerRead(0x1931800, 0xc0002c51a0, 0xc0002f2b80, 0x172cee0, 0xc000044ba0, 0xc0001aee00, 0xc0001aee70, 0x0)
2021-02-18T22:13:20.427-0500 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: 	github.com/kvrhdn/terraform-provider-honeycombio/honeycombio/resource_trigger.go:162 +0x267
2021-02-18T22:13:20.427-0500 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: github.com/kvrhdn/terraform-provider-honeycombio/honeycombio.resourceTriggerCreate(0x1931800, 0xc0002c51a0, 0xc0002f2b80, 0x172cee0, 0xc000044ba0, 0xc0002feb90, 0x12c635a, 0xc0004a9200)
2021-02-18T22:13:20.427-0500 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: 	github.com/kvrhdn/terraform-provider-honeycombio/honeycombio/resource_trigger.go:143 +0x295
2021-02-18T22:13:20.427-0500 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc00039c6e0, 0x1931780, 0xc0002e2500, 0xc0002f2b80, 0x172cee0, 0xc000044ba0, 0x0, 0x0, 0x0)
2021-02-18T22:13:20.427-0500 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.4/helper/schema/resource.go:276 +0x1ec
2021-02-18T22:13:20.427-0500 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00039c6e0, 0x1931780, 0xc0002e2500, 0xc0001ae380, 0xc0004a9200, 0x172cee0, 0xc000044ba0, 0x0, 0x0, 0x0, ...)
2021-02-18T22:13:20.427-0500 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.4/helper/schema/resource.go:387 +0x681
2021-02-18T22:13:20.427-0500 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: github.com/hashicorp/terraform-plugin-sdk/v2/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc000262200, 0x1931780, 0xc0002e2500, 0xc00013df80, 0xc000262200, 0xc000262210, 0x1849f90)
2021-02-18T22:13:20.427-0500 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.4/internal/helper/plugin/grpc_provider.go:952 +0x8b2
2021-02-18T22:13:20.427-0500 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: github.com/hashicorp/terraform-plugin-sdk/v2/internal/tfplugin5._Provider_ApplyResourceChange_Handler.func1(0x1931780, 0xc0002e2500, 0x17dfc00, 0xc00013df80, 0xc0002e2500, 0x1763a00, 0xc0002c4c01, 0xc0004a8f40)
2021-02-18T22:13:20.427-0500 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.4/internal/tfplugin5/tfplugin5.pb.go:3312 +0x86
2021-02-18T22:13:20.427-0500 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: github.com/hashicorp/terraform-plugin-sdk/v2/plugin.Serve.func3.1(0x1931840, 0xc0002e9050, 0x17dfc00, 0xc00013df80, 0xc0004a8f20, 0xc0004a8f40, 0xc000330ba0, 0x11b92e8, 0x17b8500, 0xc0002e9050)
2021-02-18T22:13:20.427-0500 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.4/plugin/serve.go:76 +0x87
2021-02-18T22:13:20.427-0500 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: github.com/hashicorp/terraform-plugin-sdk/v2/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x17ee100, 0xc000262200, 0x1931840, 0xc0002e9050, 0xc0002c4cc0, 0xc000810a20, 0x1931840, 0xc0002e9050, 0xc0001f26c0, 0x223)
2021-02-18T22:13:20.428-0500 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.4/internal/tfplugin5/tfplugin5.pb.go:3314 +0x14b
2021-02-18T22:13:20.428-0500 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001fcfc0, 0x1939c80, 0xc000703e00, 0xc000310100, 0xc000712510, 0x1e30ce0, 0x0, 0x0, 0x0)
2021-02-18T22:13:20.428-0500 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: 	google.golang.org/grpc@v1.30.0/server.go:1171 +0x50a
2021-02-18T22:13:20.428-0500 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: google.golang.org/grpc.(*Server).handleStream(0xc0001fcfc0, 0x1939c80, 0xc000703e00, 0xc000310100, 0x0)
2021-02-18T22:13:20.428-0500 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: 	google.golang.org/grpc@v1.30.0/server.go:1494 +0xccd
2021-02-18T22:13:20.428-0500 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000b4310, 0xc0001fcfc0, 0x1939c80, 0xc000703e00, 0xc000310100)
2021-02-18T22:13:20.428-0500 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: 	google.golang.org/grpc@v1.30.0/server.go:834 +0xa1
2021-02-18T22:13:20.428-0500 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-02-18T22:13:20.428-0500 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: 	google.golang.org/grpc@v1.30.0/server.go:832 +0x204
2021-02-18T22:13:20.428-0500 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021/02/18 22:13:20 [DEBUG] honeycombio_trigger.trigger: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2021/02/18 22:13:20 [TRACE] EvalMaybeTainted: honeycombio_trigger.trigger encountered an error during creation, so it is now marked as tainted
2021/02/18 22:13:20 [TRACE] EvalWriteState: removing state object for honeycombio_trigger.trigger
2021/02/18 22:13:20 [TRACE] EvalApplyProvisioners: honeycombio_trigger.trigger has no state, so skipping provisioners
2021/02/18 22:13:20 [TRACE] EvalMaybeTainted: honeycombio_trigger.trigger encountered an error during creation, so it is now marked as tainted
2021/02/18 22:13:20 [TRACE] EvalWriteState: removing state object for honeycombio_trigger.trigger
2021/02/18 22:13:20 [TRACE] vertex "honeycombio_trigger.trigger": visit complete
2021/02/18 22:13:20 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/kvrhdn/honeycombio\"] (close)" errored, so skipping
2021/02/18 22:13:20 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2021/02/18 22:13:20 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021-02-18T22:13:20.429-0500 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/kvrhdn/honeycombio/0.1.2/darwin_amd64/terraform-provider-honeycombio_v0.1.2 pid=40062 error="exit status 2"
2021/02/18 22:13:20 [TRACE] statemgr.Filesystem: not making a backup, because the new snapshot is identical to the old
2021/02/18 22:13:20 [TRACE] statemgr.Filesystem: no state changes since last snapshot
2021/02/18 22:13:20 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2021/02/18 22:13:20 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2021/02/18 22:13:20 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2021-02-18T22:13:20.446-0500 [DEBUG] plugin: plugin exited
```

When I review the list of triggers in Honeycomb, I can see that the trigger was successfully created as expected. It seems like there may be a failure on reading the trigger from the honeycomb API after it is created.

**Comment by kvrhdn** [comment] 2021-02-19 11:20
Hi, thank you for reporting this issue. You are right: the provider causes an error when it tries to read the query after it has been created. The code that throws the exception: https://github.com/kvrhdn/terraform-provider-honeycombio/blob/68a8d55b7e158591ce087baa247b4dbd134dfbfc/honeycombio/resource_trigger.go#L162-L164

Thanks to your Terraform config I was able to reproduce this on my own datasets. When I run the apply with logging enabled (`TF_LOG=debug HONEYCOMBIO_DEBUG=true terraform apply`) I noticed that the response payload from Honeycomb has changed 🤯 

```
2021-02-19T12:11:56.159+0100 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: 2021/02/19 12:11:56 Sending request
2021-02-19T12:11:56.159+0100 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2:
2021-02-19T12:11:56.159+0100 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: GET /1/triggers/kvrhdn-terraform-provider-honeycombio/tYx279pgV8f HTTP/1.1
2021-02-19T12:11:56.159+0100 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: Host: api.honeycomb.io
2021-02-19T12:11:56.159+0100 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: User-Agent: Terraform/0.14.5 (+https://www.terraform.io) Terraform-Plugin-SDK/2.0.4 terraform-provider-honeycombio/0.1.2
2021-02-19T12:11:56.159+0100 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: Content-Type: application/json
2021-02-19T12:11:56.159+0100 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: X-Honeycomb-Team: ***
2021-02-19T12:11:56.159+0100 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: Accept-Encoding: gzip
2021-02-19T12:11:56.159+0100 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2:
2021-02-19T12:11:56.159+0100 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2:
2021-02-19T12:11:56.280+0100 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: 2021/02/19 12:11:56 Received response
2021-02-19T12:11:56.280+0100 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2:
2021-02-19T12:11:56.280+0100 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: HTTP/2.0 200 OK
2021-02-19T12:11:56.280+0100 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: Access-Control-Allow-Origin: *
2021-02-19T12:11:56.280+0100 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: Content-Type: application/json
2021-02-19T12:11:56.280+0100 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: Date: Fri, 19 Feb 2021 11:11:56 GMT
2021-02-19T12:11:56.280+0100 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: Last-Modified: Fri, 19 Feb 2021 11:11:56 GMT
2021-02-19T12:11:56.280+0100 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: Vary: Accept-Encoding
2021-02-19T12:11:56.280+0100 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2:
2021-02-19T12:11:56.280+0100 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2: {"name":"test","description":"test","frequency":120,"disabled":false,"query_id":"E2fFNGt1wMo","threshold":{"op":">","value":300000},"id":"tYx279pgV8f"}
2021-02-19T12:11:56.280+0100 [DEBUG] plugin.terraform-provider-honeycombio_v0.1.2:
```

I will contact Honeycomb support.

**Comment by kvrhdn** [comment] 2021-02-22 16:40
Hi, @ssherbondy this issue was caused by a too early release of a new API (see the Pollinators Slack for more details).  The folks at Honeycomb have disabled the feature flag again, so this error shouldn't occur anymore.

I'll close the issue but feel free to open it again or create a new one if the Terraform provider is still crashing.

**Closed by kvrhdn** 2021-02-22 16:40 UTC
